from typing import Protocol, AsyncIterator

class SpeechToText(Protocol):
    async def transcribe(self, audio: bytes) -> tuple[str,str]: ...

class StreamingSpeechToText(Protocol):
    async def stream(self, chunks: AsyncIterator[bytes]) -> AsyncIterator[str]: ...

class TextToSpeech(Protocol):
    async def synthesize(self, text: str, language: str) -> bytes: ...

class Translator(Protocol):
    async def translate(self, text: str, target_language: str, literal=False) -> str: ...

class Maps(Protocol):
    async def route(self, origin: str, destination: str, mode: str) -> dict: ...

class Transit(Protocol):
    async def journeys(self, origin: str, destination: str, when=None) -> list[dict]: ...

class RideHailing(Protocol):
    async def estimates(self, origin: str, destination: str) -> list[dict]: ...
    async def handoff(self, option_id: str) -> str: ...
